SELECT ID_EQUIPAMENTO,	
		TIPO_ID,	
		TIPO_DESC,	
		--DT_ATUALIZACAO,
		ROW_NUMBER() OVER(PARTITION BY ID_EQUIPAMENTO ORDER BY TIPO_ID DESC)
FROM VW_EQUIPAMENTO
ORDER BY ID_EQUIPAMENTO, TIPO_DESC


CREATE OR REPLACE VIEW SILVER_EQUIPAMENTOS AS

SELECT
   -- ID_EQUIPAMENTO,    TIPO_ID,    TIPO_NEGOCIO,    DT_ATUALIZACAO
TIPO_NEGOCIO,
COUNT(ID_EQUIPAMENTO) AS QTDE
    
FROM (

    SELECT
        E.ID_EQUIPAMENTO,
        E.TIPO_ID,
        D.TIPO_NEGOCIO,
        E.DT_ATUALIZACAO

      --  ROW_NUMBER() OVER (
        --    PARTITION BY E.ID_EQUIPAMENTO
          --  ORDER BY E.TIPO_ID DESC
        --) AS RN

    FROM VW_EQUIPAMENTO E
    LEFT JOIN DIM_TIPO_EQUIPAMENTO D ON E.TIPO_ID = D.TIPO_ID

) X

--WHERE RN = 1
GROUP BY TIPO_NEGOCIO


NK SK 
3   1-CARRECADEIRA
10
80